apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: b-system-pipeline-combined-app1- #pipeline-run name
  namespace: b-system-cicd-demo #namespace
spec:
  params:
    - name: IMAGE_NAME
      value: 'jp.icr.io/cti-roks-training/b-sys-combined-app1:latest'
    - name: GIT_REPO
      value: 'https://github.com/cti-roks/b-system-combined-app1.git'
    - name: GIT_REVISION
      value: main
  pipelineRef:
    name:  b-system-pipeline-combined-app1
  workspaces:
    - name: workspace
      persistentVolumeClaim:
        claimName: sample-pvc-1
